apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-2
      auth:
        # Using IAM Role for ServiceAccount (recommended)
        jwt:
          serviceAccountRef:
            name: favor3-eso
            namespace: favor3-dev
