apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-env-secret
  namespace: favor3-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: ghcr-env-secret
    creationPolicy: Owner
  data:
    - secretKey: GHCR_PAT
      remoteRef:
        key: favor3-dev-ghcr-pat
