apiVersion: v1
kind: Service
metadata:
  name: favor3
  namespace: favor3-dev # change per env
spec:
  selector:
    app: favor3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
